[[redirects]]
    from = "/api/*"
    to = "https://project-fullstack-javascript-e-commerce-production.up.railway.app//api/:splat" # Your production backend API URL
    status = 200
    force = true # Optional: ensures the redirect happens even if a file exists at the path

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200